# Generated by Django 5.1.1 on 2024-10-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Triathlon_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('swim', models.DurationField()),
                ('T1', models.DurationField()),
                ('cycle', models.DurationField()),
                ('T2', models.DurationField()),
                ('run', models.DurationField()),
            ],
        ),
    ]
